export const DARK_MODE_ON = "DARK_MODE_ON";
export const DARK_MODE_OFF = "DARK_MODE_OFF";
export const SHOW_FEATURES = "SHOW_FEATURE";

export const START_UPLOAD = "START_UPLOAD";
export const START_UPLOADS = "START_UPLOADS";
export const UPDATE_UPLOAD_PROGRESS = "UPDATE_UPLOAD_PROGRESS";
export const FINISH_UPLOAD = "FINISH_UPLOAD";
export const REMOVE_UPLOAD = "REMOVE_UPLOAD";

export const CONFIG_CHANGE = "CONFIG_CHANGE";

export const OPEN_EXHAUSTER = "OPEN_EXHAUSTER";
export const CLOSE_EXHAUSTER = "CLOSE_EXHAUSTER";

export const ADD_FEATURES = "ADD_FEATURES";
export const DELETE_FEATURE = "DELETE_FEATURE";
export const SUBMIT_FEATURE = "SUBMIT_FEATURE";
export const CHANGE_FEATURE_PROP = "CHANGE_FEATURE_PROP";
export const REMOVE_PROPERTY_FROM_FEATURE = "REMOVE_PROPERTY_FROM_FEATURE";
export const INIT_FEATURES = "INIT_FEATURES";

export const HIDE_BASELAYER = "HIDE_BASELAYER";
export const SHOW_BASELAYER = "SHOW_BASELAYER";

export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";